module.exports.DISCORD_INVITES = Object.freeze({
  support: "https://discord.gg/8c4p6xcjru",
  privacy: "https://discord.gg/sQs8FhcTGh"
})

module.exports.DEFAULT_BOT_PREFIX = 'lc.'

module.exports.PRIVACY_POLICY_SECTIONS = [
  'labsCore does not collect any sort of data about its users.',
  'If the bot encounters unexpected errors we report information about the server, channel, user and command/command arguments (excluding images) to a private log in order to assist with debugging and resolving the issue. You can reference the provided error ID in our support server for further details. Contents of these automated reports will never be shared with third parties and are only accessible to the bots developers.',
  `Images modified via our proprietary api are never stored outside of the channel you executed the command in.`
]

module.exports.PRIVACY_POLICY_LAST_UPDATE = 1655325547140

module.exports.COLORS = Object.freeze({
  error: 15548997,
  success: 6411359,
  warning: 16426522,
  embed: 2829617,
  brand: 6085465,
  nsfw: 15549056
})

module.exports.ICONS = Object.freeze({
  "error": "<:ico_error:925832574239121429>",
  "warning": "<:ico_warning:925832574931189830>",
  "success": "<:ico_check:925813919929491516>",
  "success_simple": "<:lc_success:699608002910617670>",
  "failiure": "<:ico_cross:925813919577153639>",
  "failiure_simple": "<:lc_denied:688071041787887647>",
  "activity": "<:ico_activity:903266937247780906>",
  "analytics": "<:ico_analytics:914630522326642761>",
  "audio": "<:ico_audio:903260568037769286>",
  "boost": "<:ico_boost:903266056154513428>",
  "calendar": "<:ico_calendar:903263528557887528>",
  "channel": "<:ico_channel:903265030647210044>",
  "check": "<:ico_check:925813919929491516>",
  "command": "<:ico_command:903266599694372875>",
  "connection": "<:ico_connection:903282945551388702>",
  "cross": "<:ico_cross:925813919577153639>",
  "downloading": "<:ico_downloading:903301897027452998>",
  "fun": "<:ico_fun:903260112657981510>",
  "house": "<:ico_house:903263528591429702>",
  "image": "<:ico_image:903259583475240961>",
  "info": "<:ico_info:903258571335147592>",
  "list": "<:ico_list:903263528662757426>",
  "list_large": "<:ico_list_large:903265635155443772>",
  "microphone": "<:ico_microphone:903273971993169920>",
  "moderation": "<:ico_moderation:903273971523387404>",
  "nitro": "<:ico_nitro:903263528696283168>",
  "note": "<:ico_note:914630523828179034>",
  "nsfw": "<:ico_nsfw:925817891260072026>",
  "pencil": "<:ico_pencil:903273971636662313>",
  "people": "<:ico_people:915666775700561990>",
  "person": "<:ico_person:903275266485420082>",
  "qr": "<:ico_qr:915278046293000253>",
  "rocket": "<:ico_rocket:914631573238865980>",
  "role": "<:ico_role:903273016455209040>",
  "rules": "<:ico_rules:915269410699243560>",
  "search": "<:ico_search:903258998432731146>",
  "snowsgiving": "<:ico_snowsgiving:915666777646694440>",
  "stats": "<:ico_stats:903265030752047144>",
  "timer": "<:ico_timer:915271575274680350>",
  "util": "<:ico_util:903259395381690379>",
  "locale": "<:ico_locale:925891616986791936>",
  "question": "<:ico_question:949420315677691934>",
  "upvote": "<:ico_upvote:980238682353205259>",
  "downvote": "<:ico_downvote:980238681971494963>",
  "reddit_gold": "<:rdt_gold:993630360527196251>",
  "reddit_silver": "<:rdt_silver:993630364327231628>",
  "reddit_wholesome": "<:rdt_wholesome:993630485379031061>",
  "reddit_helpful": "<:rdt_helpful:993630362372677774>",
  "online": "<:ico_online:994362211772399736>",
  "offline": "<:ico_offline:994362210061123598>",
  "link": "<:ico_link:994364481792647229>",
  "robot": "<:ico_robot:1002944678112530547>",
  "robouser": "<:ico_robouser:1002944679744131092>",
  "lock": "<:ico_lock:1002948236971085924>",
  "badge_slash": "<:badge_slash:1002954716315140167>",
  "flag": "<:ico_flag:1002957495138009251>",
  "like": "<:ico_like:1086443586700181514>",
  "message": "<:ico_message:1086443588784758844>",
  "eye": "<:ico_eye:1086443585337036860>",
  "videos": "<:ico_videos:1086449271609503764>",
  "question_large": "<:ico_question:1086624956235919391>",
  "exclaim_0": "<:ico_w0:1086624957586489364>",
  "exclaim_1": "<:ico_w1:1086624959142580275>",
  "exclaim_2": "<:ico_w2:1086624961025810485>",
  "exclaim_3": "<:ico_w3:1086624963047460874>",
  "exclaim_4": "<:ico_w4:1086624964284788787>",
  "arrow_up": "<:ico_arrowup:980237911171674193>",
  "arrow_down": "<:ico_arrowdown:980237911008092160>",
  "arrow_left": "<:ico_arrowleft:1086628775644647464>",
  "arrow_right": "<:ico_arrowright:1086628777880191016>",
  "sticker": "<:ico_sticker:1096937131793985546> ",
  "emoji": "<:ico_emoji:1096936794731315251>"
})

const GUILD_FEATURE_ICONS = Object.freeze({
  ACTIVITY: "<:activity:995078510492266606>",
  AUDIO: "<:audio:995073876381945986>",
  ANIMATED: "<:animated:995034549895569519> ",
  IMAGE: "<:image:995034797112041563>",
  DIRECTORY: "<:directory:995069080467939329>",
  EMOJI: "<:emoji:995036031923539979>",
  EDUCATION: "<:education:995069345577312266>",
  BOOST: "<:boost:995068901794783234>",
  STAFF: "<:staff:995068645430534174>",
  HOME: "<:home:995068501192622150>",
  MOD: "<:mod:995068318161575957>",
  ROLE_SUBSCRIPTIONS: "<:rolesubs:995071222071181444>",
  STAR: "<:star:995071826373910568>",
  STICKER: "<:sticker:995072116405842040>",
  ROLE_ICONS: "<:roleicons:995072431695863819>",
  VERIFIED: "<:verified:995073342350577674>",
  PARTNER: "<:partner:995073343554338867>",
  WALLET: "<:wallet:995075115681329213>",
  TAG: "<:tag:995075110660751370>",
  TICKET: "<:ticket:995075114372694016>",
  THREAD: "<:thread:995075113030529065>",
  PRIVATE_THREAD: "<:privatethread:995075107712143410>",
  CLOCK: "<:clock:995075106328035519>",
  EYE: "<:eye:995076484555345920>",
  EYE_HIDDEN: "<:eyehidden:995076486832857219>",
  GLOBE: "<:globe:995076489542377623>",
  MEGAPHONE: "<:mega:995076487789154396>",
  DISCOVERY: "<:discovery:995077771619471480>",
  DISCOVERY_DISABLED: "<:discoveryoff:995077769836888116>",
  DISCOVERY_ENABLED: "<:discoveryon:995077768029155480>",
  WAVE: "<:wave:995079620468670554>",
  PROFILE: "<:profile:995080477734088855>",
  MESSAGE: "<:message:995080756021952594>",
  BOT_DEVELOPER: "<:botdev:995081351457935391>",
  PEOPLE_RED: "<:peoplered:995081367098499103>",
  SLASH_COMMAND: "<:slash:1049583205621174282>",
  HIGHLIGHT: "<:highlight:1049584669110325290>",
  TIMEOUT: "<:timeout:1049585531278856202>",
  SOUNDBOARD: "<:soundboard:1049591390989983784>"
})

module.exports.GUILD_FEATURES = Object.freeze({
  "ACTIVITIES_ALPHA": { icon: GUILD_FEATURE_ICONS.ACTIVITY },
  "ACTIVITIES_EMPLOYEE": { icon: GUILD_FEATURE_ICONS.ACTIVITY },
  "ACTIVITIES_INTERNAL_DEV": { icon: GUILD_FEATURE_ICONS.ACTIVITY },
  "ANIMATED_BANNER": { icon: GUILD_FEATURE_ICONS.ANIMATED },
  "ANIMATED_ICON": { icon: GUILD_FEATURE_ICONS.ANIMATED },
  "APPLICATION_COMMAND_PERMISSIONS_V2": { icon: GUILD_FEATURE_ICONS.SLASH_COMMAND },
  "AUTO_MODERATION": { icon: GUILD_FEATURE_ICONS.MOD },
  "AUTOMOD_TRIGGER_KEYWORD_FILTER": { icon: GUILD_FEATURE_ICONS.MOD, name: "Automod Keywords Filter" },
  "AUTOMOD_TRIGGER_ML_SPAM_FILTER": { icon: GUILD_FEATURE_ICONS.MOD, name: "Automod ML Spam Filter" },
  "AUTOMOD_TRIGGER_SPAM_LINK_FILTER": { icon: GUILD_FEATURE_ICONS.MOD, name: "Automod Spam Link Filter" },
  "BANNER": { icon: GUILD_FEATURE_ICONS.IMAGE, name: "Server Banner" },
  "BFG": { icon: GUILD_FEATURE_ICONS.GLOBE, name: "Very Large Server" },
  "BOOSTING_TIERS_EXPERIMENT_MEDIUM_GUILD": { icon: GUILD_FEATURE_ICONS.BOOST },
  "BOOSTING_TIERS_EXPERIMENT_SMALL_GUILD": { icon: GUILD_FEATURE_ICONS.BOOST },
  "BOT_DEVELOPER_EARLY_ACCESS": { icon: GUILD_FEATURE_ICONS.BOT_DEVELOPER, name: "Bot Developer Testing" },
  "CHANNEL_BANNER": { icon: GUILD_FEATURE_ICONS.IMAGE, name: "Channel Banners" },
  "CHANNEL_HIGHLIGHTS": { icon: GUILD_FEATURE_ICONS.HIGHLIGHT },
  "COMMERCE": { icon: GUILD_FEATURE_ICONS.TAG, name: "Store Channels" },
  "COMMUNITY": { icon: GUILD_FEATURE_ICONS.GLOBE },
  "COMMUNITY_EXP_LARGE_GATED": { icon: GUILD_FEATURE_ICONS.GLOBE, name: "Community Experiment - Large Gated" },
  "COMMUNITY_EXP_LARGE_UNGATED": { icon: GUILD_FEATURE_ICONS.GLOBE, name: "Community Experiment - Large Ungated" },
  "CREATOR_MONETIZABLE": { icon: GUILD_FEATURE_ICONS.WALLET },
  "CREATOR_MONETIZABLE_DISABLED": { icon: GUILD_FEATURE_ICONS.WALLET },
  "CREATOR_MONETIZABLE_PROVISIONAL": { icon: GUILD_FEATURE_ICONS.WALLET },
  "CREATOR_MONETIZABLE_WHITEGLOVE": { icon: GUILD_FEATURE_ICONS.WALLET },
  "CREATOR_MONETIZATION_APPLICATION_ALLOWLIST": { icon: GUILD_FEATURE_ICONS.WALLET },
  "CREATOR_STORE_PAGE": { icon: GUILD_FEATURE_ICONS.WALLET },
  "DEVELOPER_SUPPORT_SERVER": { icon: GUILD_FEATURE_ICONS.BOT_DEVELOPER },
  "DISCOVERABLE": { icon: GUILD_FEATURE_ICONS.DISCOVERY_ENABLED, name: "Discovery" },
  "DISCOVERABLE_DISABLED": { icon: GUILD_FEATURE_ICONS.DISCOVERY_DISABLED, name: "Discovery Disabled" },
  "ENABLED_DISCOVERABLE_BEFORE": { icon: GUILD_FEATURE_ICONS.DISCOVERY, name: "Has been in Discovery" },
  "EXPOSED_TO_ACTIVITIES_WTP_EXPERIMENT": { icon: GUILD_FEATURE_ICONS.ACTIVITY },
  "EXPOSED_TO_BOOSTING_TIERS_EXPERIMENT": { icon: GUILD_FEATURE_ICONS.BOOST },
  "FEATURABLE": { icon: GUILD_FEATURE_ICONS.STAR },
  "FORCE_RELAY": { icon: "🏃💨", name: "Relay Force Enabled" },
  "GUILD_AUTOMOD_DEFAULT_LIST": { icon: GUILD_FEATURE_ICONS.MOD },
  "GUILD_COMMUNICATION_DISABLED_GUILDS": { icon: GUILD_FEATURE_ICONS.TIMEOUT, name: "Timeouts" },
  "GUILD_HOME_TEST": { icon: GUILD_FEATURE_ICONS.HOME },
  "GUILD_HOME_OVERRIDE": { icon: GUILD_FEATURE_ICONS.HOME },
  "GUILD_MEMBER_VERIFICATION_EXPERIMENT": { icon: GUILD_FEATURE_ICONS.EYE },
  "GUILD_ONBOARDING": { icon: GUILD_FEATURE_ICONS.DISCOVERY },
  "GUILD_ONBOARDING_ADMIN_ONLY": { icon: GUILD_FEATURE_ICONS.DISCOVERY, name: "Guild Onboarding Admin Override" },
  "GUILD_ONBOARDING_EVER_ENABLED": { icon: GUILD_FEATURE_ICONS.DISCOVERY },
  "GUILD_ROLE_SUBSCRIPTION_TRIALS": { icon: GUILD_FEATURE_ICONS.ROLE_SUBSCRIPTIONS, name: "Role Subscription Trials" },
  "GUILD_ROLE_SUBSCRIPTION_PURCHASE_FEEDBACK_LOOP": { icon: GUILD_FEATURE_ICONS.ROLE_SUBSCRIPTIONS, name: "Role Subscription Feedback Loop" },
  "GUILD_ROLE_SUBSCRIPTIONS": { icon: GUILD_FEATURE_ICONS.ROLE_SUBSCRIPTIONS, name: "Role Subscriptions" },
  "HAD_EARLY_ACTIVITIES_ACCESS": { icon: GUILD_FEATURE_ICONS.ACTIVITY },
  "HAS_DIRECTORY_ENTRY": { icon: GUILD_FEATURE_ICONS.DIRECTORY },
  "HUB": { icon: GUILD_FEATURE_ICONS.EDUCATION, name: "School Hub" },
  "INCREASED_THREAD_LIMIT": { icon: GUILD_FEATURE_ICONS.THREAD },
  "INTERNAL_EMPLOYEE_ONLY": { icon: GUILD_FEATURE_ICONS.STAFF, name: "Internal Employee Server" },
  "INVITE_SPLASH": { icon: GUILD_FEATURE_ICONS.IMAGE },
  "INVITES_DISABLED": { icon: GUILD_FEATURE_ICONS.DISCOVERY_DISABLED },
  "LINKED_TO_HUB": { icon: GUILD_FEATURE_ICONS.DIRECTORY },
  "MEMBER_PROFILES": { icon: GUILD_FEATURE_ICONS.PROFILE },
  "MEMBER_VERIFICATION_GATE_ENABLED": { icon: GUILD_FEATURE_ICONS.WAVE, name: "Membership Screening" },
  "MEMBER_VERIFICATION_MANUAL_APPROVAL": { icon: GUILD_FEATURE_ICONS.WAVE, name: "Membership Screening Manual Approval" },
  "MOBILE_WEB_ROLE_SUBSCRIPTION_PURCHASE_PAGE": { icon: GUILD_FEATURE_ICONS.ROLE_SUBSCRIPTIONS, name: "Mobile Role Subscriptions Purchase Page" },
  "MONETIZATION_ENABLED": { icon: GUILD_FEATURE_ICONS.WALLET },
  "MORE_EMOJI": { icon: GUILD_FEATURE_ICONS.EMOJI },
  "MORE_STICKERS": { icon: GUILD_FEATURE_ICONS.STICKER },
  "NEWS": { icon: GUILD_FEATURE_ICONS.MEGAPHONE, name: "Announcement Channels" },
  "NEW_THREAD_PERMISSIONS": { icon: GUILD_FEATURE_ICONS.THREAD },
  "PARTNERED": { icon: GUILD_FEATURE_ICONS.PARTNER },
  "PREMIUM_TIER_3_OVERRIDE": { icon: GUILD_FEATURE_ICONS.STAFF },
  "PREVIEW_ENABLED": { icon: GUILD_FEATURE_ICONS.EYE },
  "PRIVATE_THREADS": { icon: GUILD_FEATURE_ICONS.PRIVATE_THREAD },
  "RAID_ALERTS_ENABLED": { icon: GUILD_FEATURE_ICONS.MOD },
  "RESTRICT_SPAM_RISK_GUILDS": { icon: GUILD_FEATURE_ICONS.EYE_HIDDEN },
  "RELAY_ENABLED": { icon: "🏃" },
  "ROLE_ICONS": { icon: GUILD_FEATURE_ICONS.ROLE_ICONS },
  "ROLE_SUBSCRIPTIONS_AVAILABLE_FOR_PURCHASE": { icon: GUILD_FEATURE_ICONS.ROLE_SUBSCRIPTIONS },
  "ROLE_SUBSCRIPTIONS_ENABLED": { icon: GUILD_FEATURE_ICONS.ROLE_SUBSCRIPTIONS, name: "Role Subscriptions" },
  "SEVEN_DAY_THREAD_ARCHIVE": { icon: GUILD_FEATURE_ICONS.CLOCK, name: "7 Day Thread Archiving" },
  "SOUNDBOARD": { icon: GUILD_FEATURE_ICONS.SOUNDBOARD },
  "TEXT_IN_STAGE_ENABLED": { icon: GUILD_FEATURE_ICONS.MESSAGE, name: "Text in Stages" },
  "TEXT_IN_VOICE_ENABLED": { icon: GUILD_FEATURE_ICONS.MESSAGE, name: "Text in Voice" },
  "THREAD_DEFAULT_AUTO_ARCHIVE_DURATION": { icon: GUILD_FEATURE_ICONS.CLOCK },
  "THREADS_ENABLED": { icon: GUILD_FEATURE_ICONS.THREAD },
  "THREADS_ENABLED_TESTING": { icon: GUILD_FEATURE_ICONS.THREAD, name: "Thread Testing Enabled" },
  "THREADS_ONLY_CHANNEL": { icon: GUILD_FEATURE_ICONS.THREAD },
  "THREE_DAY_THREAD_ARCHIVE": { icon: GUILD_FEATURE_ICONS.CLOCK, name: "3 Day Thread Archiving" },
  "TICKETED_EVENTS_ENABLED": { icon: GUILD_FEATURE_ICONS.TICKET },
  "VANITY_URL": { icon: GUILD_FEATURE_ICONS.STAR, name: "Vanity URL" },
  "VERIFIED": { icon: GUILD_FEATURE_ICONS.VERIFIED },
  "VIP_REGIONS": { icon: GUILD_FEATURE_ICONS.AUDIO, name: "VIP Regions" },
  "VOICE_CHANNEL_EFFECTS": { icon: GUILD_FEATURE_ICONS.STAR },
  "WELCOME_SCREEN_ENABLED": { icon: GUILD_FEATURE_ICONS.WAVE },
  "LURKABLE": { icon: GUILD_FEATURE_ICONS.EYE, name: "Lurking Enabled" },
  "MEMBER_LIST_DISABLED": { icon: GUILD_FEATURE_ICONS.PEOPLE_RED },
  "PUBLIC_DISABLED": { icon: GUILD_FEATURE_ICONS.GLOBE },
  "PUBLIC": { icon: GUILD_FEATURE_ICONS.GLOBE },
  "ROLE_SUBSCRIPTIONS_ENABLED_FOR_PURCHASE": { icon: GUILD_FEATURE_ICONS.ROLE_SUBSCRIPTIONS },
  "TICKETING_ENABLED": { icon: GUILD_FEATURE_ICONS.TICKET }
})

module.exports.TIKTOK_VOICES = [
  { name: "English Singing - Tenor", value: "en_male_m03_lobby" },
  { name: "English Singing - Alto", value: "en_female_f08_salut_damour" },
  { name: "English Singing - Warmy Breeze", value: "en_female_f08_warmy_breeze" },
  { name: "English Singing - Sunshine Soon", value: "en_male_m03_sunshine_soon" },
  { name: "English Narration - Normal", value: "en_male_narration" },
  { name: "English Narration - Funny", value: "en_male_funny" },
  { name: "English Narration - Emotional", value: "en_female_emotional" },
  { name: "English AU - Female", value: "en_au_001" },
  { name: "English AU - Male", value: "en_au_002" },
  { name: "English UK - Male", value: "en_uk_001" },
  { name: "English US - Female", value: "en_us_001" },
  { name: "English US - Male", value: "en_us_006" },
  { name: "Ghost Face (Disney)", value: "en_us_ghostface" },
  { name: "Chewbacca (Disney)", value: "en_us_chewbacca" },
  { name: "C3PO (Disney)", value: "en_us_c3po" },
  { name: "Stitch (Disney)", value: "en_us_stitch" },
  { name: "Stormtrooper (Disney)", value: "en_us_stormtrooper" },
  { name: "Rocket (Disney)", value: "en_us_rocket" },
  { name: "French - Male", value: "fr_001" },
  { name: "German - Female", value: "de_001" },
  { name: "German - Male", value: "de_002" },
  { name: "Spanish - Male", value: "es_002" },
  { name: "Spanish MX - Male", value: "es_mx_002" }
]

module.exports.PLAYHT_VOICES = [
  { name: "Conrad (German)", value: "de-DE-ConradNeural" }
]

module.exports.IMTRANSLATOR_VOICES = [
  { name: "English (Male)", value: "en" },
  { name: "English (Female)", value: "enf" },
  { name: "Chinese (Female)", value: "zh" },
  { name: "Spanish (Carlos)", value: "es" },
  { name: "Russian (Female)", value: "ru" },
  { name: "French (Female)", value: "fr" },
  { name: "German (Male)", value: "de" },
  { name: "Italian (Male)", value: "it" },
  { name: "Portugese (Female)", value: "pt" },
  { name: "Japanese (Female)", value: "ja" },
  { name: "Korean (Female)", value: "ko" }
]

module.exports.MICROSOFT_VOICES = [
  { name: "Microsoft Sam", value: "Sam" },
  { name: "BonziBUDDY", value: "Bonzi" },
  { name: "Mary", value: "Mary" },
  { name: "Mike", value: "Mike" },
  { name: "Robot", value: "RoboSoft Four" },
  { name: "Whisper (Female)", value: "Female Whisper" },
  { name: "Whisper (Male)", value: "Male Whisper" }
]

module.exports.MICROSOFT_VOICE_CONFIG = {
  "Sam": { pitch: 100, speed: 150 },
  "Bonzi": { pitch: 140, speed: 157 },
  "Mary": { pitch: 169, speed: 170 },
  "Mike": { pitch: 113, speed: 170 },
  "RoboSoft Four": { pitch: 169, speed: 170 },
  "Female Whisper": { pitch: 169, speed: 170 },
  "Male Whisper": { pitch: 113, speed: 170 }
}

module.exports.TRANSLATE_LANGUAGE_MAPPINGS = Object.freeze({
  "af": "🇿🇦",
  "sq": "🇦🇱",
  "am": "🇪🇹",
  "ar": "",
  "hy": "🇦🇲",
  "as": "",
  "ay": "",
  "az": "🇦🇿",
  "bm": "",
  "eu": "Basque",
  "be": "🇧🇾",
  "bn": "🇧🇩",
  "bho": "",
  "bs": "🇧🇦",
  "bg": "🇧🇬",
  "ca": "",
  "ceb": "🇵🇭",
  "zh-CN or zh": "",
  "zh-TW": "",
  "co": "",
  "hr": "🇭🇷",
  "cs": "🇨🇿",
  "da": "🇩🇰",
  "dv": "",
  "doi": "",
  "nl": "🇳🇱",
  "en": "🇺🇸",
  "eo": "",
  "et": "🇪🇪",
  "ee": "",
  "fil": "🇵🇭",
  "fi": "🇫🇮",
  "fr": "🇫🇷",
  "fy": "",
  "gl": "",
  "ka": "🇬🇪",
  "de": "🇩🇪",
  "el": "🇬🇷",
  "gn": "",
  "gu": "",
  "ht": "🇭🇹",
  "ha": "🇳🇬",
  "haw": "",
  "he or iw": "",
  "hi": "🇮🇳",
  "hmn": "",
  "hu": "🇭🇺",
  "is": "🇮🇸",
  "ig": "🇳🇬",
  "ilo": "",
  "id": "🇮🇩",
  "ga": "🇮🇪",
  "it": "🇮🇹",
  "ja": "🇯🇵",
  "jv or jw": "",
  "kn": "",
  "kk": "🇰🇿",
  "km": "🇰🇭",
  "rw": "",
  "gom": "",
  "ko": "🇰🇷",
  "kri": "",
  "ku": "",
  "ckb": "",
  "ky": "🇰🇬",
  "lo": "🇱🇦",
  "la": "",
  "lv": "🇱🇻",
  "ln": "",
  "lt": "🇱🇹",
  "lg": "",
  "lb": "🇱🇺",
  "mk": "🇲🇰",
  "mai": "",
  "mg": "🇲🇬",
  "ms": "🇲🇾",
  "ml": "",
  "mt": "🇲🇹",
  "mi": "🇳🇿",
  "mr": "🇮🇳",
  "mn": "🇲🇳",
  "my": "🇲🇲",
  "ne": "🇳🇵",
  "no": "🇳🇴",
  "ny": "🇲🇼",
  "ps": "🇦🇫",
  "fa": "🇮🇷",
  "pl": "🇵🇱",
  "pt": "🇵🇹",
  "ro": "🇷🇴",
  "ru": "🇷🇺",
  "sm": "🇼🇸",
  "sa": "",
  "gd": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "nso": "",
  "sr": "🇷🇸",
  "st": "🇱🇸",
  "sn": "🇿🇼",
  "si": "🇱🇰",
  "sk": "🇸🇰",
  "sl": "🇸🇮",
  "so": "🇸🇴",
  "es": "🇪🇸",
  "su": "🇸🇩",
  "sw": "🇰🇪",
  "sv": "🇸🇪",
  "tl": "🇵🇭",
  "tg": "🇹🇯",
  "te": "🇮🇳",
  "th": "🇹🇭",
  "ti": "🇪🇷",
  "ts": "🇹🇴",
  "tr": "🇹🇷",
  "tk": "🇹🇲",
  "ak": "🇬🇭",
  "uk": "🇺🇦",
  "ur": "🇵🇰",
  "uz": "🇺🇿",
  "vi": "🇻🇳",
  "cy": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  "xh": "🇿🇦",
  "yo": "🇳🇬",
  "zu": "🇿🇦",
  "zh-TW": "🇨🇳",
  "zh": "🇨🇳",
  "zh-CN": "🇨🇳",
})

module.exports.TRANSLATE_LANGUAGES = Object.freeze({
  'auto': 'Automatic',
  "af": "Afrikaans",
  "sq": "Albanian",
  "am": "Amharic",
  "ar": "Arabic",
  "hy": "Armenian",
  "as": "Assamese",
  "ay": "Aymara",
  "az": "Azerbaijani",
  "bm": "Bambara",
  "eu": "Basque",
  "be": "Belarusian",
  "bn": "Bengali",
  "bho": "Bhojpuri",
  "bs": "Bosnian",
  "bg": "Bulgarian",
  "ca": "Catalan",
  "ceb": "Cebuano",
  "zh-CN": "Chinese",
  "zh": "Chinese",
  "zh-TW": "Chinese (Traditional)",
  "co": "Corsican",
  "hr": "Croatian",
  "cs": "Czech",
  "da": "Danish",
  "dv": "Dhivehi",
  "doi": "Dogri",
  "nl": "Dutch",
  "en": "English",
  "eo": "Esperanto",
  "et": "Estonian",
  "ee": "Ewe",
  "fil": "Filipino (Tagalog)",
  "fi": "Finnish",
  "fr": "French",
  "fy": "Frisian",
  "gl": "Galician",
  "ka": "Georgian",
  "de": "German",
  "el": "Greek",
  "gn": "Guarani",
  "gu": "Gujarati",
  "ht": "Haitian Creole",
  "ha": "Hausa",
  "haw": "Hawaiian",
  "he or iw": "Hebrew",
  "hi": "Hindi",
  "hmn": "Hmong",
  "hu": "Hungarian",
  "is": "Icelandic",
  "ig": "Igbo",
  "ilo": "Ilocano",
  "id": "Indonesian",
  "ga": "Irish",
  "it": "Italian",
  "ja": "Japanese",
  "jv or jw": "Javanese",
  "kn": "Kannada",
  "kk": "Kazakh",
  "km": "Khmer",
  "rw": "Kinyarwanda",
  "gom": "Konkani",
  "ko": "Korean",
  "kri": "Krio",
  "ku": "Kurdish",
  "ckb": "Kurdish (Sorani)",
  "ky": "Kyrgyz",
  "lo": "Lao",
  "la": "Latin",
  "lv": "Latvian",
  "ln": "Lingala",
  "lt": "Lithuanian",
  "lg": "Luganda",
  "lb": "Luxembourgish",
  "mk": "Macedonian",
  "mai": "Maithili",
  "mg": "Malagasy",
  "ms": "Malay",
  "ml": "Malayalam",
  "mt": "Maltese",
  "mi": "Maori",
  "mr": "Marathi",
  "mni-Mtei": "Meiteilon (Manipuri)",
  "lus": "Mizo",
  "mn": "Mongolian",
  "my": "Myanmar (Burmese)",
  "ne": "Nepali",
  "no": "Norwegian",
  "ny": "Nyanja (Chichewa)",
  "or": "Odia (Oriya)",
  "om": "Oromo",
  "ps": "Pashto",
  "fa": "Persian",
  "pl": "Polish",
  "pt": "Portuguese (Portugal, Brazil)",
  "pa": "Punjabi",
  "qu": "Quechua",
  "ro": "Romanian",
  "ru": "Russian",
  "sm": "Samoan",
  "sa": "Sanskrit",
  "gd": "Scots Gaelic",
  "nso": "Sepedi",
  "sr": "Serbian",
  "st": "Sesotho",
  "sn": "Shona",
  "sd": "Sindhi",
  "si": "Sinhala (Sinhalese)",
  "sk": "Slovak",
  "sl": "Slovenian",
  "so": "Somali",
  "es": "Spanish",
  "su": "Sundanese",
  "sw": "Swahili",
  "sv": "Swedish",
  "tl": "Tagalog (Filipino)",
  "tg": "Tajik",
  "ta": "Tamil",
  "tt": "Tatar",
  "te": "Telugu",
  "th": "Thai",
  "ti": "Tigrinya",
  "ts": "Tsonga",
  "tr": "Turkish",
  "tk": "Turkmen",
  "ak": "Twi (Akan)",
  "uk": "Ukrainian",
  "ur": "Urdu",
  "ug": "Uyghur",
  "uz": "Uzbek",
  "vi": "Vietnamese",
  "cy": "Welsh",
  "xh": "Xhosa",
  "yi": "Yiddish",
  "yo": "Yoruba",
  "zu": "Zulu"
  })

module.exports.EMOJIPEDIA_PLATFORM_TYPES = [
  "apple",
  "google",
  "samsung",
  "joypixels",
  "microsoft",
  "facebook",
  "twitter",
  "whatsapp",
  "lg",
  "mozilla",
  "htc",
  "emojidex",
  "messenger",
  "softbank",
  "au-kddi",
  "docomo",
  "openmoji",
  "skype",
  "sony",
  "noto-emoji",
  "toss-face",
  "microsoft-teams",
  "animated-noto-color-emoji",
  "twitter-emoji-stickers",
  "emojipedia"
]

module.exports.EMOJIPEDIA_PLATFORM_TYPE_ALIASES = {
  "fluent": "microsoft-teams",
  "twemoji": "twitter",
  "playstation": "sony",
  "ios": "apple",
  "android": "google",
  "windows": "microsoft"
}

module.exports.GOOGLE_CLOUD_SAFETY_LABELS_NAMES = Object.freeze({
  "adult":    "Explicit Content ",
  "spoof":    "Modified Image   ",
  "medical":  "Medical Image    ",
  "violence": "Contains Violence",
  "racy":     "Lewd Content     "
})

module.exports.GOOGLE_CLOUD_SAFETY_LABELS = Object.freeze({
  "UNKNOWN": {
    icon: "question_large",
    name: "Unknown      "
  },
  "VERY_UNLIKELY": {
    icon: "exclaim_0",
    name: "Very Unlikely"
  },
  "UNLIKELY": {
    icon: "exclaim_1",
    name: "Unlikely     "
  },
  "POSSIBLE": {
    icon: "exclaim_2",
    name: "Possible     "
  },
  "LIKELY": {
    icon: "exclaim_3",
    name: "Likely       "
  },
  "VERY_LIKELY": {
    icon: "exclaim_4",
    name: "Very Likely  "
  }
})

module.exports.MAPKIT_ACTIONS = Object.freeze({
  SEARCH: "search",
  STATIC_MAP: "render"
})

module.exports.REXTESTER_LANGUAGES = Object.freeze({
  "bash": "38",
  "node": "23",
  "js": "23",
  "py": "5",
  "java": "4",
  "lua": "14",
  "ruby": "12",
  "perl": "13",
  "go": "20",
  //"kt": "43",
  "rust": "46",
  "php": "8",
  "c": "6",
  "cpp": "7",
  'cs': "1",
  "elixir": "41",
  "swift": "37",
  "bf": "44",
  "scala": "21",
  "haskell": "11"
})

module.exports.REXTESTER_COMPILER_ARGS = Object.freeze({
  "6": "-Wall -std=gnu99 -O2 -o a.out source_file.c",
  "7": "-Wall -std=c++14 -O2 -o a.out source_file.cpp",
  "11": "-o a.out source_file.hs"
})

const { Permissions } = require("detritus-client/lib/constants")

module.exports.PERMISSIONS_TEXT = Object.freeze({
  [Permissions.ADD_REACTIONS]: "Add Reactions",
  [Permissions.ADMINISTRATOR]: "Administrator",
  [Permissions.ATTACH_FILES]: "Attach Files",
  [Permissions.BAN_MEMBERS]: "Ban Members",
  [Permissions.CHANGE_NICKNAME]: "Change Nickname",
  [Permissions.CHANGE_NICKNAMES]: "Change Nicknames",
  [Permissions.CONNECT]: "Connect",
  [Permissions.CREATE_INSTANT_INVITE]: "Create Invites",
  [Permissions.DEAFEN_MEMBERS]: "Deafen Members",
  [Permissions.EMBED_LINKS]: "Embed Links",
  [Permissions.KICK_MEMBERS]: "Kick Members",
  [Permissions.MANAGE_CHANNELS]: "Manage Channels",
  [Permissions.MANAGE_EMOJIS]: "Manage Emojis",
  [Permissions.MANAGE_GUILD]: "Manage Guild",
  [Permissions.MANAGE_MESSAGES]: "Manage Messages",
  [Permissions.MANAGE_ROLES]: "Manage Roles",
  [Permissions.MANAGE_WEBHOOKS]: "Manage Webhooks",
  [Permissions.MENTION_EVERYONE]: "Mention Everyone",
  [Permissions.MOVE_MEMBERS]: "Move Members",
  [Permissions.MUTE_MEMBERS]: "Mute Members",
  [Permissions.NONE]: "None",
  [Permissions.PRIORITY_SPEAKER]: "Priority Speaker",
  [Permissions.READ_MESSAGE_HISTORY]: "Read Message History",
  [Permissions.SEND_MESSAGES]: "Send Messages",
  [Permissions.SEND_TTS_MESSAGES]: "Text-To-Speech",
  [Permissions.SPEAK]: "Speak",
  [Permissions.STREAM]: "Go Live",
  [Permissions.USE_EXTERNAL_EMOJIS]: "Use External Emojis",
  [Permissions.USE_VAD]: "Voice Auto Detect",
  [Permissions.VIEW_AUDIT_LOG]: "View Audit Logs",
  [Permissions.VIEW_CHANNEL]: "View Channel",
  [Permissions.VIEW_GUILD_ANALYTICS]: "View Server Insights"
});
