module.exports.DISCORD_INVITES = Object.freeze({
  support: "https://discord.gg/8c4p6xcjru",
  privacy: "https://discord.gg/sQs8FhcTGh",
  invite: "https://discord.gg/cHd28DrM7f",
  help: "https://discord.gg/xQNBB3WFne"
})

module.exports.DEFAULT_BOT_NAME = 'labsCore'

// The first prefix in this list is considered the
// default prefix and will be displayed in various
// places throughout the app
module.exports.DEFAULT_PREFIXES = ['lc.', 'ic.', 'pb.']

module.exports.PRIVACY_POLICY_SECTIONS = [
  '### Summary\n- We do not store or collect information about our users or their servers.\n- We share certain data with third parties that is strictly necessary to operate certain functionality.',
  '### The information we collect\nWe use technology to log unexpected issues that may occur when interacting with our application. These logs are only shared with the developers of the application and not accessible to the public. Logged information includes:\n- Your username, server and channel\n- The command you executed, as well as its arguments (excluding images)',
  'Images modified via our proprietary api are directly uploaded to Discord and never permanently stored anywhere other than the requested channel by us.\n- The only exception to this is the art command, wallpapers generated via art will be publicly shared in the support server for anyone to view.)',
  '### Third Parties\nWe use a variety of third party products and services to operate certain functionality of our application. Information shared with third parties is strictly limited to information necessary to provide the functionality (command arguments).\nWe do not offer any functionality that shares details about users, a channel or a server with third parties and their services.'
]

module.exports.PRIVACY_POLICY_LAST_UPDATE = 1699120509970
module.exports.PRIVACY_POLICY_PREVIOUS_REVISION = "privacy_june22.1dborzeh8yhs"

module.exports.SUPPORT_ARTICLES = {
  AGE_RESTRICTED_CHANNELS: 115000084051
}

module.exports.OPEN_SOURCE_REPOSITORY_URL = "https://gitlab.com/bignutty/labscore"

module.exports.COLORS = Object.freeze({
  error: 15548997,
  success: 8191849,
  warning: 16426522,
  embed: 2829617,
  brand: 6809687,
  nsfw: 15549056,
  incognito: 10057726,
})

module.exports.BADGE_ICONS = Object.freeze({
  "active_developer": "<:b:1263607989873414196>",
  "bot_developer": "<:b:1263605652337463489>",
  "bug_hunter": "<:b:1263605576773013616>",
  "bug_hunter_lvl2": "<:b:1263607090501517372>",
  "early_supporter": "<:b:1263607076173905950>",
  "hypesquad_events": "<:b:1263607076173905950>",
  "hypesquad_balance": "<:b:1263607122659119255>",
  "hypesquad_bravery": "<:b:1263607134596104273>",
  "hypesquad_brilliance": "<:b:1263607149721026600>",
  "mod_program": "<:b:1263605447001243698> ",
  "nitro": "<:b:1263607232558399631>",
  "partner": "<:b:1263605756356464751>",
  "staff": "<:b:1263605715688231035>"
})

module.exports.ICONS = Object.freeze({
  "brand": "<:ico_brand_2024:1263593574478643221>",
  "flask_incognito": "<:ico_flask_incognito:1263608937459224688>",
  
  "flask_mini": "<:ico_subt_flask:1263593669215256597>",
  "subtext_lightbulb": "<:ico_subt_lightbulb:1263593690358616084>",

  "button_thermometer": "<:ico_button_thermometer:1263593823016062987>",
  "button_user_profile_swap": "<:ico_button_user_profile_swap:1263594003442700368>",

  "button_chevron_left": "<:button_chevron_left:1263594121256374413>",
  "button_chevron_right": "<:button_chevron_right:1263594132023279669>",

  "home": "<:ico_home:1263593114694586400>",
  "image": "<:ico_image:1263593101755289610>",
  "search": "<:ico_search:1263593084810301493>",
  "shield": "<:ico_shield:1263593069530583171>",
  "stars": " <:ico_stars:1263593055512957122>",
  "tools": "<:ico_tools:1263593031903346698>",

  "agreements": "<:ico_agreements:1263592506017189988>",
  "calendar": "<:ico_calendar:1263592493505577041>",
  "certificate": "<:ico_certificate:1263592480461553794>",
  "clock": "<:ico_clock:1263592462841020537>",
  "definition": "<:ico_definition:1263592450136473684>",
  "example": "<:ico_example:1263592408021471253>",
  "flag": "<:ico_flag:1263592391630127114>",
  "list": "<:ico_list:1263592365994803306>",
  "mag": "<:ico_mag:1263592345845108747>",
  "note": "<:ico_note:1263592327856001105>",
  "padlock": "<:ico_padlock:1263592313280528434>",
  "pencil": "<:ico_pencil:1263592296570421351>",
  "planet": "<:ico_planet:1263592281685098568>",
  "qr": "<:ico_qr:1263592268053348393>",
  "robot": "<:ico_robot:1263592241776164893>",
  "settings": "<:ico_settings:1263592222784356402>",
  "trend": "<:ico_trend:1263592191981256786>",
  "visible": "<:ico_visible:1263592172436066374>",

  "activity": "<:ico_activity:1263591756570689682>",
  "attachment": "<:ico_attachment:1263591742452666378>",
  "boost": "<:ico_boost:1263591721741193226>",
  "discord": "<:ico_discord:1263591704439689226>",
  "emoji": "<:ico_emoji:1263591687691833479>",
  "link": "<:ico_link:1263591669727629406>",
  "locale": "<:ico_locale:1263591655143903314>",
  "message": "<:ico_message:1263591634537545788>",
  "nitro": "<:ico_nitro:1263591618603126865>",
  "reply": "<:ico_reply:1263591597778407474>",
  "slash": "<:ico_slash:1263591582884434091>",
  "sticker": "<:ico_sticker:1263591567676145754>",

  "audio": "<:ico_audio:1263591286779412480>",
  "channel": "<:ico_channel:1263591268211097662>",
  "channel_nsfw": "<:ico_channel_nsfw:1263591241057173514>",
  "mention": "<:ico_mention:1263591215429849189>",
  "microphone": "<:ico_microphone:1263591199911051427>",

  "user": "<:ico_user:1263590776617828462>",
  "user_card": "<:ico_user_card:1263590467166277698>",
  "user_king": "<:ico_user_king:1263590410228334637>",
  "user_multiple": "<:ico_user_multiple:1263590373754929162>",
  "user_profile": "<:ico_user_profile:1263590325927284827>",
  "user_shield": "<:ico_user_shield:1263590283552231444>",

  "status_offline": "<:ico_status_offline:1263590209644134520>",
  "status_online": "<:ico_status_online:1263590195333169204>",

  "arrow_down": "<:ico_arrow_down:1263589989778853928>",
  "arrow_left": "<:ico_arrow_left:1263590017159139339>",
  "arrow_right": "<:ico_arrow_right:1263590004886863902>",
  "arrow_up": "<:ico_arrow_up:1263590030174195833>",

  "stat_comments": "<:ico_stat_comments:1263589816407162911>",
  "stat_likes": "<:ico_stat_likes:1263589802289397903>",
  "stat_people": "<:ico_stat_people:1263589790251618434>",
  "stat_videos": "<:ico_stat_videos:1263589779258216508>",
  "stat_views": "<:ico_stat_views:1263589767900299385>",

  "downvote": "<:ico_downvote:1263589702171103242>",
  "upvote": "<:ico_upvote:1263589685243154515>",

  "gitlab": "<:ico_gitlab:1263589629999976561>",

  "generative_ai": "<:ico_generative_ai:1263589586387468349>",
  "latency": "<:ico_latency:1263589536139710566>",

  "moon": "<:ico_moon:1263589209059496137> ",
  "sun": "<:ico_sun:1263589195251716116> ",

  "exclaim_0": "<:ico_exclaim_0:1263588923670532106>",
  "exclaim_1": "<:ico_exclaim_1:1263588911754510538>",
  "exclaim_2": "<:ico_exclaim_2:1263588899670855712>",
  "exclaim_3": "<:ico_exclaim_3:1263588890485457046>",
  "exclaim_4": "<:ico_exclaim_4:1263588879307640883>",
  "question_large": "<:ico_question_large:1263589058999750787>",

  "weather_blizzard": "<:ico_w_blizzard:1263583584850022460>",
  "weather_blowing_snow": "<:ico_w_blowing_snow:1263583671726903377>",
  "weather_clear_day": "<:ico_w_clear_day:1263583684158820383>",
  "weather_clear_night": "<:ico_w_clear_night:1263583704069181622>",
  "weather_cloudy": "<:ico_w_cloudy:1263583715704180879>",
  "weather_drizzle": "<:ico_w_drizzle:1263583728769302609>",
  "weather_flurries": "<:ico_w_flurries:1263583744053215333>",
  "weather_haze_fog_dust_smoke": "<:ico_w_haze_fog_dust_smoke:1263583772885127188>",
  "weather_heavy_rain": "<:ico_w_heavy_rain:1263583786428399717>",
  "weather_heavy_snow": "<:ico_w_heavy_snow:1263583800957337640>",
  "weather_icy": "<:ico_w_icy:1263583815717359658>",
  "weather_isolated_scattered_thunderstorms_day": "<:ico_w_iso_scattered_tstorm_day:1263583831433150526>",
  "weather_isolated_scattered_thunderstorms_night": "<:ico_w_iso_scattered_tstorm_night:1263584235847942246>",
  "weather_isolated_thunderstorms": "<:ico_w_isolated_thunderstorms:1263584283264548986>",
  "weather_mixed_rain_hail_sleet": "<:ico_w_mixed_rain_sleet_hail:1263584310598959185>",
  "weather_mixed_rain_snow": "<:ico_w_mixed_rain_snow:1263584323752296468>",
  "weather_mostly_clear_day": "<:ico_w_mostly_clear_day:1263584337471864986>",
  "weather_mostly_clear_night": "<:ico_w_mostly_clear_night:1263584621493489784>",
  "weather_mostly_cloudy_day": "<:ico_w_mostly_cloudy_day:1263584634793623575>",
  "weather_mostly_cloudy_night": "<:ico_w_mostly_cloudy_night:1263584648508866662>",
  "weather_partly_cloudy_day": "<:ico_w_partly_cloudy_day:1263584669644095558>",
  "weather_partly_cloudy_night": "<:ico_w_partly_cloudy_night:1263584672844087316>",
  "weather_scattered_showers_day": "<:ico_w_scattered_showers_day:1263584683657134101>",
  "weather_scattered_showers_night": "<:ico_w_scattered_showers_night:1263584693555560478>",
  "weather_scattered_snow_showers_day": "<:ico_w_scattered_snow_showers_day:1263584731178467449> ",
  "weather_scattered_snow_showers_night": "<:ico_scattered_snow_showers_night:1263584941996904448>",
  "weather_showers_rain": "<:ico_w_showers_rain:1263584960359567381>",
  "weather_showers_snow": "<:ico_w_snow_showers_snow:1263584991552471171>",
  "weather_sleet_hail": "<:ico_w_sleet_hail:1263584973697581140>",
  "weather_strong_thunderstorms": "<:ico_w_strong_tstorms:1263585008589869056>",
  "weather_tornado": "<:ico_w_tornado:1263585022552707154>",
  "weather_tropical_storm_hurricane": "<:ico_w_tropical_storm_hurricane:1263585036058366003>",
  "weather_very_cold": "<:ico_w_very_cold:1263588188513898582>",
  "weather_very_hot": "<:very_hot:1263588713838018652>",
  "weather_windy": "<:ico_w_windy_breezy:1263585171849084968>",

  "information": "<:ico_information:1263590946226835510>",
  "question": "<:ico_question:1263590898906697800>",
  "warning": "<:ico_warning:1263590857072967832>",

  // Internal Icons
  "empty": "<:ico_empty:1263591098740113478>",

  // Legacy Icon Compat
  "success_simple": "<:ico_check:1263594912692178974>",
  "failiure_simple": "<:ico_cross:1263594899048235100>"
})

module.exports.GUILD_FEATURE_ICONS_REDESIGN = Object.freeze({
  "ActivitiesIcon": "<:ico_d_activities:1263595238929334272>",
  "AnnouncementsIcon": "<:ico_d_announcements:1263595270684545205>",
  "BadgeIcon": "<:ico_d_badge:1263595290363957342>",
  "BeakerIcon": "<:ico_d_beaker:1263595306184867840>",
  "BillIcon": "<:ico_d_bill:1263595324090482719>",
  "BoostTier3Icon": "<:iico_d_boosttier3:1263595349667352668>",
  "BrowserIcon": "<:ico_d_browser:1263595374778515649>",
  "CircleQuestionIcon": "<:ico_d_circlequestion:1263595522921337025>",
  "ClockWarningIcon": "<:ico_d_clockwarning:1263595576520474714>",
  "CompassIcon": "<:ico_d_compass:1263595614122409984>",
  "ForumIcon": "<:ico_d_forum:1263595652680650824> ",
  "GameControllerIcon": "<:ico_d_gamecontroller:1263595688323846225>",
  "GifIcon": "<:ico_d_gif:1263595715129643129>",
  "GlobeEarthIcon": "<:ico_d_globeearth:1263595760054960161>",
  "GroupIcon": "<:ico_d_group:1263595799275770007>",
  "HomeIcon": "<:ico_d_home:1263596088821026938>",
  "HubIcon": "<:ico_d_hub:1263596112229568512>",
  "ImagesIcon": "<:ico_d_images:1263596134061051935>",
  "LinkIcon": "<:ico_d_link:1263596153434407032>",
  "NewUserLargeIcon": "<:ico_d_newuserlarge:1263596178725933137>",
  "PaintbrushThickIcon": "<:ico_d_paintbrushthick:1263596221524869164>",
  "PartnerIcon": "<:ico_dc_partnerflowerbadge:1263601192643199077>",
  "PiggyBankIcon": "<:ico_d_piggybank:1263596275853688944>",
  "ReactionIcon": "<:ico_d_reaction:1263596296544194703>",
  "RobotIcon": "<:ico_d_robot:1263596312314777782>",
  "ServerIcon": "<:ico_d_server:1263596330400354314>",
  "ShieldIcon": "<:ico_d_shield:1263596397924712570>",
  "ShieldUserIcon": "<:ico_d_shielduser:1263596413829386292>",
  "SignPostIcon": "<:ico_d_signpost:1263596376554737674>",
  "SlashBoxIcon": "<:ico_d_slashbox:1263596429432328273>",
  "SoundboardIcon": "<:ico_d_soundboard:1263596446301683825>",
  "SparklesIcon": "<:ico_d_sparkles:1263596462764462192>",
  "StaffBadgeIcon": "<:ico_d_staffbadge:1263596482519502868>",
  "SuperReactionIcon": "<:ico_d_superreaction:1263596497283579957>",
  "TagIcon": "<:ico_d_tag:1263596510994501745>",
  "TextIcon": "<:ico_d_text:1263596525288685579>",
  "ThreadIcon": "<:ico_d_thread:1263596544486146068>",
  "TicketIcon": "<:ico_d_ticket:1263596560172716103>",
  "TopicsIcon": "<:ico_d_topics:1263596574978867240>",
  "TreehouseIcon": "<:ico_d_treehouse:1263596587763105843>",
  "UserIcon": "<:ico_d_user:1263596600891281510>",
  "UserPlusIcon": "<:ico_d_userplus:1263596620059246752>",
  "UserShieldIcon": "<:ico_d_usershield:1263596641450066051>",
  "VerifiedIcon": "<:ico_dc_verifiedflowerbadge:1263600898685272184>",
  "VoiceIcon": "<:ico_d_voicenormal:1263596678087446548>",
})

module.exports.GUILD_FEATURES = Object.freeze({
  "ACTIVITIES_ALPHA": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ActivitiesIcon },
  "ACTIVITIES_EMPLOYEE": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ActivitiesIcon },
  "ACTIVITIES_INTERNAL_DEV": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ActivitiesIcon },
  "ANIMATED_BANNER": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.GifIcon },
  "ANIMATED_ICON": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.GifIcon },
  "APPLICATION_COMMAND_PERMISSIONS_V2": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.SlashBoxIcon, label: "New Slash Command Permissions" },
  "AUTOMOD_TRIGGER_KEYWORD_FILTER": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ShieldIcon },
  "AUTOMOD_TRIGGER_ML_SPAM_FILTER": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ShieldIcon },
  "AUTOMOD_TRIGGER_SPAM_LINK_FILTER": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ShieldIcon },
  "AUTOMOD_TRIGGER_USER_PROFILE": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ShieldIcon },
  "AUTO_MODERATION": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ShieldIcon, label: "Automod" },
  "BANNER": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ImagesIcon, label: "Server Banner" },
  "BFG": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ServerIcon, label: "Really Big Server" },
  "BOOSTING_TIERS_EXPERIMENT_MEDIUM_GUILD": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.BoostTier3Icon },
  "BOOSTING_TIERS_EXPERIMENT_SMALL_GUILD": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.BoostTier3Icon },
  "BOT_DEVELOPER_EARLY_ACCESS": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.RobotIcon },
  "BURST_REACTIONS": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.SuperReactionIcon },
  "CHANNEL_BANNER": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ImagesIcon },
  "CHANNEL_EMOJIS_GENERATED": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ReactionIcon },
  "CHANNEL_HIGHLIGHTS": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.SparklesIcon },
  "CHANNEL_HIGHLIGHTS_DISABLED": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.SparklesIcon },
  "CHANNEL_ICON_EMOJIS_GENERATED": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ReactionIcon },
  "CLAN": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ShieldUserIcon },
  "CLYDE_DISABLED": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.RobotIcon },
  "CLYDE_ENABLED": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.RobotIcon },
  "CLYDE_EXPERIMENT_ENABLED": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.RobotIcon },
  "COMMERCE": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.TagIcon, label: "Store Channels" },
  "COMMUNITY": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.TreehouseIcon },
  "COMMUNITY_CANARY": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.TreehouseIcon },
  "COMMUNITY_EXP_MEDIUM": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.TreehouseIcon, label: "Communities, Medium Server" },
  "COMMUNITY_EXP_LARGE_GATED": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.TreehouseIcon, label: "Communities, Large Gated Server" },
  "COMMUNITY_EXP_LARGE_UNGATED": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.TreehouseIcon, label: "Communities, Large Ungated Server" },
  "CREATOR_ACCEPTED_NEW_TERMS": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.BillIcon },
  "CREATOR_MONETIZABLE": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.BillIcon },
  "CREATOR_MONETIZABLE_DISABLED": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.BillIcon },
  "CREATOR_MONETIZABLE_PENDING_NEW_OWNER_ONBOARDING": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.BillIcon },
  "CREATOR_MONETIZABLE_PROVISIONAL": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.BillIcon },
  "CREATOR_MONETIZABLE_RESTRICTED": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.BillIcon },
  "CREATOR_MONETIZABLE_WHITEGLOVE": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.BillIcon },
  "CREATOR_MONETIZATION_APPLICATION_ALLOWLIST": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.BillIcon },
  "CREATOR_STORE_PAGE": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.BrowserIcon },
  "DEVELOPER_SUPPORT_SERVER": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.RobotIcon },
  "DISCOVERABLE": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.CompassIcon },
  "DISCOVERABLE_DISABLED": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.CompassIcon },
  "ENABLED_DISCOVERABLE_BEFORE": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.CompassIcon, label: "Discovery previously enabled" },
  "ENABLED_MODERATION_EXPERIENCE_FOR_NON_COMMUNITY": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ShieldIcon },
  "EXPOSED_TO_ACTIVITIES_WTP_EXPERIMENT": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ActivitiesIcon },
  "EXPOSED_TO_BOOSTING_TIERS_EXPERIMENT": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.BoostTier3Icon },
  "FEATURABLE": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.CompassIcon },
  "FORCE_RELAY": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ServerIcon, label: "Relay force enabled" },
  "GENSHIN_L30": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.GameControllerIcon },
  "GUESTS_ENABLED": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.GroupIcon },
  "GUILD_AUTOMOD_DEFAULT_LIST": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ShieldIcon , label: "Automod default list"},
  "GUILD_COMMUNICATION_DISABLED_GUILDS": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ClockWarningIcon, label: "Timeouts enabled" },
  "GUILD_HOME_DEPRECATION_OVERRIDE": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.HomeIcon, label: "Home Deprecation Override" },
  "GUILD_HOME_OVERRIDE": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.HomeIcon, label: "Home Override" },
  "GUILD_HOME_TEST": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.HomeIcon, label: "Home Test" },
  "GUILD_MEMBER_VERIFICATION_EXPERIMENT": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.UserShieldIcon },
  "GUILD_ONBOARDING": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.NewUserLargeIcon, label: "Onboarding" },
  "GUILD_ONBOARDING_ADMIN_ONLY": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.NewUserLargeIcon, label: "Onboarding admin only" },
  "GUILD_ONBOARDING_EVER_ENABLED": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.NewUserLargeIcon, label: "Onboarding previously enabled" },
  "GUILD_ONBOARDING_HAS_PROMPTS": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.NewUserLargeIcon, label: "Onboarding has prompts" },
  "GUILD_PRODUCTS": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.PiggyBankIcon, label: "Server Products" },
  "GUILD_ROLE_SUBSCRIPTIONS": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.BadgeIcon, label: "Role Subscriptions" },
  "GUILD_ROLE_SUBSCRIPTION_PURCHASE_FEEDBACK_LOOP": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.BadgeIcon, label: "Role Subscriptions Feedback" },
  "GUILD_ROLE_SUBSCRIPTION_TIER_TEMPLATE": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.BadgeIcon, label: "Role Subscriptions Tier Template" },
  "GUILD_ROLE_SUBSCRIPTION_TRIALS": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.BadgeIcon, label: "Role Subscriptions Trials" },
  "GUILD_SERVER_GUIDE": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.SignPostIcon, label: "Server Guide" },
  "GUILD_WEB_PAGE_VANITY_URL": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.GlobeEarthIcon, label: "Server Web Page Vanity URL" },
  "HAD_EARLY_ACTIVITIES_ACCESS": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ActivitiesIcon },
  "HAS_DIRECTORY_ENTRY": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.HubIcon },
  "HIDE_FROM_EXPERIMENT_UI": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.BeakerIcon },
  "HUB": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.HubIcon, label: "Student Hub" },
  "INCREASED_THREAD_LIMIT": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ThreadIcon },
  "INTERNAL_EMPLOYEE_ONLY": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.StaffBadgeIcon },
  "INVITES_DISABLED": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.LinkIcon },
  "INVITE_SPLASH": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ImagesIcon },
  "LINKED_TO_HUB": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.HubIcon },
  "LURKABLE": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.CompassIcon },
  "MARKETPLACES_CONNECTION_ROLES": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ShieldUserIcon },
  "MEMBER_LIST_DISABLED": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.GroupIcon },
  "MEMBER_PROFILES": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.UserIcon },
  "MEMBER_SAFETY_PAGE_ROLLOUT": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.GroupIcon },
  "MEMBER_VERIFICATION_GATE_ENABLED": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.UserShieldIcon, label: "Membership Screening" },
  "MEMBER_VERIFICATION_MANUAL_APPROVAL": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.UserShieldIcon, label: "Membership Screening Manual Approval" },
  "MOBILE_WEB_ROLE_SUBSCRIPTION_PURCHASE_PAGE": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.BrowserIcon, label: "Role Subscriptions Web Page enabled" },
  "MONETIZATION_ENABLED": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.BillIcon },
  "MORE_EMOJI": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ReactionIcon },
  "MORE_STICKERS": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ReactionIcon },
  "NEWS": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.AnnouncementsIcon, label: "Announcement Channels" },
  "NEW_THREAD_PERMISSIONS": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ThreadIcon },
  "NON_COMMUNITY_RAID_ALERTS": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ShieldIcon },
  "PARTNERED": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.PartnerIcon },
  "PREMIUM_TIER_3_OVERRIDE": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.BoostTier3Icon },
  "PREVIEW_ENABLED": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.CompassIcon },
  "PRIVATE_THREADS": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ThreadIcon },
  "PRODUCTS_AVAILABLE_FOR_PURCHASE": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.TagIcon },
  "PUBLIC": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.CompassIcon },
  "PUBLIC_DISABLED": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.CompassIcon },
  "RAID_ALERTS_DISABLED": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ShieldIcon },
  "RAID_ALERTS_ENABLED": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ShieldIcon },
  "RELAY_ENABLED": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ServerIcon },
  "RESTRICT_SPAM_RISK_GUILDS": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.UserShieldIcon },
  "ROLE_ICONS": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ShieldUserIcon },
  "ROLE_SUBSCRIPTIONS_AVAILABLE_FOR_PURCHASE": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.BadgeIcon },
  "ROLE_SUBSCRIPTIONS_ENABLED": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.BadgeIcon },
  "ROLE_SUBSCRIPTIONS_ENABLED_FOR_PURCHASE": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.BadgeIcon },
  "SEVEN_DAY_THREAD_ARCHIVE": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ThreadIcon },
  "SHARD": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ServerIcon },
  "SHARED_CANVAS_FRIENDS_AND_FAMILY_TEST": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.PaintbrushThickIcon },
  "SOUNDBOARD": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.SoundboardIcon },
  "SUMMARIES_DISABLED_BY_USER": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.TopicsIcon },
  "SUMMARIES_ENABLED": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.TopicsIcon },
  "SUMMARIES_ENABLED_BY_USER": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.TopicsIcon },
  "SUMMARIES_ENABLED_GA": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.TopicsIcon },
  "SUMMARIES_LONG_LOOKBACK": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.TopicsIcon },
  "TEXT_IN_STAGE_ENABLED": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.TextIcon },
  "TEXT_IN_VOICE_ENABLED": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.TextIcon },
  "THREADS_ENABLED": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ThreadIcon },
  "THREADS_ENABLED_TESTING": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ThreadIcon },
  "THREADS_ONLY_CHANNEL": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ForumIcon, label: "Forum Channels" },
  "THREAD_DEFAULT_AUTO_ARCHIVE_DURATION": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ThreadIcon },
  "THREE_DAY_THREAD_ARCHIVE": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ThreadIcon },
  "TICKETED_EVENTS_ENABLED": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.TicketIcon },
  "TICKETING_ENABLED": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.TicketIcon },
  "VALORANT_L30": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.GameControllerIcon },
  "VANITY_URL": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.GlobeEarthIcon },
  "VERIFIED": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.VerifiedIcon },
  "VIP_REGIONS": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.VoiceIcon },
  "VOICE_CHANNEL_EFFECTS": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.VoiceIcon },
  "VOICE_IN_THREADS": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.ThreadIcon },
  "WELCOME_SCREEN_ENABLED": { icon: this.GUILD_FEATURE_ICONS_REDESIGN.UserPlusIcon },
})

module.exports.FUNNY_CAT_ICONS = [
  "<:ico_garf_gm:1263608611645558814>",
  "<:ico_garf_gn:1263608597179404319>",
  "<:ico_garf_funnycat:1263608584390971498>",
  "<:ico_garf_garthumbsup:1263608571929694353>"
]

module.exports.TIKTOK_VOICES_FRENCH = {
  "fr_001": "French Male 1",
  "fr_002": "French Male 2"
}

module.exports.TIKTOK_VOICES_GERMAN = {
  "de_001": "German Female",
  "de_002": "German Male"
}

module.exports.TIKTOK_VOICES_INDONESIAN = {
  "id_male_darma": "Darma",
  "id_female_icha": "Icha",
  "id_female_noor": "Noor",
  "id_male_putra": "Putra"
}

module.exports.TIKTOK_VOICES_ITALIAN = {
  "it_male_m18": "Italian Male"
}

module.exports.TIKTOK_VOICES_JAPANESE = {
  "jp_001": "Miho (美穂)",
  "jp_003": "Keiko (恵子)",
  "jp_005": "Sakura (さくら)",
  "jp_006": "Naoki (直樹)",
  "jp_male_osada": "モリスケ (Morisuke)",
  "jp_male_matsuo": "モジャオ (Matsuo)",
  "jp_female_machikoriiita": "まちこりーた (Machikoriiita)",
  "jp_male_matsudake": " マツダ家の日常 (Matsudake)",
  "jp_male_shuichiro": "修一朗 (Shuichiro)",
  "jp_female_rei": "丸山礼 (Maruyama Rei)",
  "jp_male_hikakin": "ヒカキン (Hikakin)",
  "jp_female_yagishaki": "八木沙季 (Yagi Saki)",
}

module.exports.TIKTOK_VOICES_KOREAN = {
  "kr_002": "Korean Male 1",
  "kr_004": "Korean Male 2",
  "kr_003": "Korean Female"
}

module.exports.TIKTOK_VOICES_PORTUGESE = {
  "br_003": "Júlia",
  "br_004": "Ana",
  "br_005": "Lucas",
  "pt_female_lhays": "Lhays Macedo",
  "pt_female_laizza": "Laizza",
}

module.exports.TIKTOK_VOICES_SPANISH = {
  "es_002": "Spanish Male",
  "es_male_m3": "Julio",
  "es_female_f6": "Alejandra",
  "es_female_pb1": "Mariana",
  "es_mx_002": "Álex (Warm)",
  "es_mx_female_supermom": "Super Mamá",
}

module.exports.TIKTOK_VOICES_SONG = {
  "en_male_m2_xhxs_m03_silly": "Song: Quirky Time",
  "en_female_f08_twinkle": "Song: Pop Lullaby",
  "en_male_m03_sunshine_soon": "Song: Toon Beat (Sunshine Soon)",
  "en_male_sing_funny_thanksgiving": "Song: Thanksgiving",
  "en_female_ht_f08_newyear": "Song: NYE 2023",
  "en_female_ht_f08_wonderful_world": "Song: Melodrama (Wonderful World)",
  "en_male_m03_lobby": "Song: Jingle (Lobby)",
  "en_male_sing_funny_it_goes_up": "Song: Hypetrain (It Goes Up)",
  "en_female_ht_f08_glorious": "Song: Euphoric (Glorious)",
  "en_female_ht_f08_halloween": "Song: Opera (Halloween)",
  "en_female_f08_warmy_breeze": "Song: Open Mic (Warmy Breeze)",
  "en_male_m2_xhxs_m03_christmas": "Song: Cozy",
  "en_female_f08_salut_damour": "Song: Cottagecore (Salut d'Amour)",
  "en_male_m03_classical": "Song: Classic Electric",
  "en_male_sing_deep_jingle": "Song: Caroler",
}

module.exports.TIKTOK_VOICES_POP_CULTURE = {
  "en_female_madam_leota": "Madame Leota (Haunted Mansion)",
  "en_us_rocket": "Rocket (Guardians of the Galaxy)",
  "en_us_stitch": "Stitch (Lilo & Stitch)",
  "en_us_stormtrooper": "Stormtrooper (Star Wars)",
  "en_us_c3po": "C-3PO (Star Wars)",
  "en_us_chewbacca": "Chewbacca (Star Wars)",
  "en_us_ghostface": "Ghostface (Scream)",
  "en_male_grinch": "Trickster (Grinch)",
  "en_male_ghosthost": "Ghost Host",
  "en_male_ukbutler": "Mr. Meticulous",
  "en_male_deadpool": "Mr. GoodGuy (Deadpool)",
//"en_male_petercullen": "Optimus Prime",
}

module.exports.TIKTOK_VOICES_CHARACTERS = {
  "en_female_pansino": "Varsity",
//"en_male_santa_effect": "Santa (w/ effect)",
  "en_male_santa": "Santa",
  "en_male_pirate": "Pirate",
  "en_male_trevor": "Marty",
  "en_male_wizard": "Magician",
  "en_male_ukneighbor": "Lord Cringe",
  "en_female_grandma": "Grandma",
  "en_female_shenna": "Debutante",
  "en_male_cupid": "Cupid",
//"en_female_richgirl": "Bestie",
  "en_female_makeup": "Beauty Guru",
  "en_female_betty": "Bae",
//"en_male_santa_narration": "Author",
  "en_male_jarvis": "Alfred",
  "en_male_funny": "Wacky",
  "en_male_narration": "Story Teller",
  "en_male_cody": "Serious",
  "en_female_samc": "Empathetic",
  "en_us_010": "Confidence",
  "en_us_009": "Scientist",
  "en_us_007": "Professor",
  "en_us_006": "Joey",
  "en_us_002": "Jessie",
  "en_au_002": "Smooth (Alex)",
  "en_au_001": "Metro (Eddie)",
  "en_female_emotional": "Peaceful",
  "en_uk_001": "Narrator (Chris)",
}

module.exports.TIKTOK_VOICES = [
  { name: "English Singing - Tenor", value: "en_male_m03_lobby" },
  { name: "English Singing - Alto", value: "en_female_f08_salut_damour" },
  { name: "English Singing - Warmy Breeze", value: "en_female_f08_warmy_breeze" },
  { name: "English Singing - Sunshine Soon", value: "en_male_m03_sunshine_soon" },
  { name: "English Narration - Normal", value: "en_male_narration" },
  { name: "English Narration - Funny", value: "en_male_funny" },
  { name: "English Narration - Emotional", value: "en_female_emotional" },
  { name: "English AU - Female", value: "en_au_001" },
  { name: "English AU - Male", value: "en_au_002" },
  { name: "English UK - Male", value: "en_uk_001" },
  { name: "English US - Female", value: "en_us_001" },
  { name: "English US - Male", value: "en_us_006" },
  { name: "Ghost Face (Disney)", value: "en_us_ghostface" },
  { name: "Chewbacca (Disney)", value: "en_us_chewbacca" },
  { name: "C3PO (Disney)", value: "en_us_c3po" },
  { name: "Stitch (Disney)", value: "en_us_stitch" },
  { name: "Stormtrooper (Disney)", value: "en_us_stormtrooper" },
  { name: "Rocket (Disney)", value: "en_us_rocket" },
  { name: "French - Male", value: "fr_001" },
  { name: "German - Female", value: "de_001" },
  { name: "German - Male", value: "de_002" },
  { name: "Spanish - Male", value: "es_002" },
  { name: "Spanish MX - Male", value: "es_mx_002" }
]

module.exports.PLAYHT_VOICES = [
  { name: "Conrad (German)", value: "de-DE-ConradNeural" }
]

module.exports.IMTRANSLATOR_VOICES = [
  { name: "English (Male)", value: "en" },
  { name: "English (Female)", value: "enf" },
  { name: "Chinese (Female)", value: "zh" },
  { name: "Spanish (Carlos)", value: "es" },
  { name: "Russian (Female)", value: "ru" },
  { name: "French (Female)", value: "fr" },
  { name: "German (Male)", value: "de" },
  { name: "Italian (Male)", value: "it" },
  { name: "Portugese (Female)", value: "pt" },
  { name: "Japanese (Female)", value: "ja" },
  { name: "Korean (Female)", value: "ko" }
]

module.exports.MICROSOFT_VOICES = [
  { name: "Microsoft Sam", value: "Sam" },
  { name: "BonziBUDDY", value: "Bonzi" },
  { name: "Mary", value: "Mary" },
  { name: "Mike", value: "Mike" },
  { name: "Robot", value: "RoboSoft Four" },
  { name: "Whisper (Female)", value: "Female Whisper" },
  { name: "Whisper (Male)", value: "Male Whisper" }
]

module.exports.MICROSOFT_VOICE_CONFIG = {
  "Sam": { pitch: 100, speed: 150 },
  "Bonzi": { pitch: 140, speed: 157 },
  "Mary": { pitch: 169, speed: 170 },
  "Mike": { pitch: 113, speed: 170 },
  "RoboSoft Four": { pitch: 169, speed: 170 },
  "Female Whisper": { pitch: 169, speed: 170 },
  "Male Whisper": { pitch: 113, speed: 170 }
}

module.exports.REWRITE_STYLES = [
  { name: "📝 Fix Grammar", value: "GRAMMAR" },
  { name: "🤩 Excited", value: "EXCITED" },
  { name: "😎 Chill", value: "CHILL" },
  { name: "📜 Shakespeare", value: "SHAKESPEARE" },
  { name: "📰 Shorten", value: "SHORTEN" },
  { name: "📄 Formal", value: "FORMAL" }
]


module.exports.DICTIONARY_LANGUAGES = Object.freeze({
  ar: "Arabic",
  ca: "Catalan",
  cs: "Czech",
  da: "Danish",
  de: "German",
  el: "Greek",
  "en-uk": "English (UK)",
  en: "English (US)",
  es: "Spanish",
  fi: "Finnish",
  fr: "French",
  hi: "Hindi",
  hr: "Croatian",
  id: "Indonesian",
  it: "Italian",
  iw: "Hebrew",
  ja: "Japanese",
  ko: "Korean",
  nl: "Dutch",
  no: "Norwegian",
  pl: "Polish",
  "pt-br": "Portuguese (Brazil)",
  "pt-pt": "Portuguese (Portugal)",
  pt: "Portuguese",
  ro: "Romanian",
  ru: "Russian",
  sr: "Serbian",
  sk: "Slovak",
  sv: "Swedish",
  th: "Thai",
  tl: "Tagalog",
  tr: "Turkish",
  uk: "Ukrainian",
  vi: "Vietnamese",
  "zh-cn": "Chinese",
  "zh-tw": "Chinese",
  zh: "Chinese"
})

// hey if you're looking at this and are annoyed that a language
// doesn't as expected work lmk on discord @bignutty and i'll add
// it (within reason), same goes for flag emoji below
module.exports.TRANSLATE_LANGUAGE_ALIASES = Object.freeze({
  "jp": "ja",
})

module.exports.TRANSLATE_LANGUAGE_MAPPINGS = Object.freeze({
  "af": "🇿🇦",
  "sq": "🇦🇱",
  "am": "🇪🇹",
  "ar": "",
  "hy": "🇦🇲",
  "as": "",
  "ay": "",
  "az": "🇦🇿",
  "bm": "",
  "eu": "",
  "be": "🇧🇾",
  "bn": "🇧🇩",
  "bho": "",
  "bs": "🇧🇦",
  "bg": "🇧🇬",
  "ca": "",
  "ceb": "🇵🇭",
  "co": "",
  "hr": "🇭🇷",
  "cs": "🇨🇿",
  "da": "🇩🇰",
  "dv": "",
  "doi": "",
  "nl": "🇳🇱",
  "en": "🇺🇸",
  "eo": "",
  "et": "🇪🇪",
  "ee": "",
  "fil": "🇵🇭",
  "fi": "🇫🇮",
  "fr": "🇫🇷",
  "fy": "",
  "gl": "",
  "ka": "🇬🇪",
  "de": "🇩🇪",
  "el": "🇬🇷",
  "gn": "",
  "gu": "",
  "ht": "🇭🇹",
  "ha": "🇳🇬",
  "haw": "",
  "he": "🇮🇱",
  "iw": "🇮🇱",
  "hi": "🇮🇳",
  "hmn": "",
  "hu": "🇭🇺",
  "is": "🇮🇸",
  "ig": "🇳🇬",
  "ilo": "",
  "id": "🇮🇩",
  "ga": "🇮🇪",
  "it": "🇮🇹",
  "ja": "🇯🇵",
  "jv": "",
  "kn": "",
  "kk": "🇰🇿",
  "km": "🇰🇭",
  "rw": "",
  "gom": "",
  "ko": "🇰🇷",
  "kri": "",
  "ku": "",
  "ckb": "",
  "ky": "🇰🇬",
  "lo": "🇱🇦",
  "la": "",
  "lv": "🇱🇻",
  "ln": "",
  "lt": "🇱🇹",
  "lg": "",
  "lb": "🇱🇺",
  "mk": "🇲🇰",
  "mai": "",
  "mg": "🇲🇬",
  "ms": "🇲🇾",
  "ml": "",
  "mt": "🇲🇹",
  "mi": "🇳🇿",
  "mr": "🇮🇳",
  "mn": "🇲🇳",
  "my": "🇲🇲",
  "ne": "🇳🇵",
  "no": "🇳🇴",
  "ny": "🇲🇼",
  "ps": "🇦🇫",
  "fa": "🇮🇷",
  "pl": "🇵🇱",
  "pt": "🇵🇹",
  "pt-pt": "🇵🇹",
  "pt-br": "🇧🇷",
  "ro": "🇷🇴",
  "ru": "🇷🇺",
  "sm": "🇼🇸",
  "sa": "",
  "gd": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "nso": "",
  "sr": "🇷🇸",
  "st": "🇱🇸",
  "sn": "🇿🇼",
  "si": "🇱🇰",
  "sk": "🇸🇰",
  "sl": "🇸🇮",
  "so": "🇸🇴",
  "es": "🇪🇸",
  "su": "🇸🇩",
  "sw": "🇰🇪",
  "sv": "🇸🇪",
  "tl": "🇵🇭",
  "tg": "🇹🇯",
  "te": "🇮🇳",
  "th": "🇹🇭",
  "ti": "🇪🇷",
  "ts": "🇹🇴",
  "tr": "🇹🇷",
  "tk": "🇹🇲",
  "ak": "🇬🇭",
  "uk": "🇺🇦",
  "ur": "🇵🇰",
  "uz": "🇺🇿",
  "vi": "🇻🇳",
  "cy": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  "xh": "🇿🇦",
  "yo": "🇳🇬",
  "zu": "🇿🇦",
  "zh-TW": "🇨🇳",
  "zh": "🇨🇳",
  "zh-CN": "🇨🇳",
})

module.exports.TRANSLATE_LANGUAGES = Object.freeze({
  'auto': 'Automatic',
  "af": "Afrikaans",
  "sq": "Albanian",
  "am": "Amharic",
  "ar": "Arabic",
  "hy": "Armenian",
  "as": "Assamese",
  "ay": "Aymara",
  "az": "Azerbaijani",
  "bm": "Bambara",
  "eu": "Basque",
  "be": "Belarusian",
  "bn": "Bengali",
  "bho": "Bhojpuri",
  "bs": "Bosnian",
  "bg": "Bulgarian",
  "ca": "Catalan",
  "ceb": "Cebuano",
  "zh-CN": "Chinese",
  "zh": "Chinese",
  "zh-TW": "Chinese (Traditional)",
  "co": "Corsican",
  "hr": "Croatian",
  "cs": "Czech",
  "da": "Danish",
  "dv": "Dhivehi",
  "doi": "Dogri",
  "nl": "Dutch",
  "en": "English",
  "eo": "Esperanto",
  "et": "Estonian",
  "ee": "Ewe",
  "fil": "Filipino (Tagalog)",
  "fi": "Finnish",
  "fr": "French",
  "fy": "Frisian",
  "gl": "Galician",
  "ka": "Georgian",
  "de": "German",
  "el": "Greek",
  "gn": "Guarani",
  "gu": "Gujarati",
  "ht": "Haitian Creole",
  "ha": "Hausa",
  "haw": "Hawaiian",
  "he": "Hebrew",
  "iw": "Hebrew",
  "hi": "Hindi",
  "hmn": "Hmong",
  "hu": "Hungarian",
  "is": "Icelandic",
  "ig": "Igbo",
  "ilo": "Ilocano",
  "id": "Indonesian",
  "ga": "Irish",
  "it": "Italian",
  "ja": "Japanese",
  "jv": "Javanese",
  "kn": "Kannada",
  "kk": "Kazakh",
  "km": "Khmer",
  "rw": "Kinyarwanda",
  "gom": "Konkani",
  "ko": "Korean",
  "kri": "Krio",
  "ku": "Kurdish",
  "ckb": "Kurdish (Sorani)",
  "ky": "Kyrgyz",
  "lo": "Lao",
  "la": "Latin",
  "lv": "Latvian",
  "ln": "Lingala",
  "lt": "Lithuanian",
  "lg": "Luganda",
  "lb": "Luxembourgish",
  "mk": "Macedonian",
  "mai": "Maithili",
  "mg": "Malagasy",
  "ms": "Malay",
  "ml": "Malayalam",
  "mt": "Maltese",
  "mi": "Maori",
  "mr": "Marathi",
  "mni-Mtei": "Meiteilon (Manipuri)",
  "lus": "Mizo",
  "mn": "Mongolian",
  "my": "Myanmar (Burmese)",
  "ne": "Nepali",
  "no": "Norwegian",
  "ny": "Nyanja (Chichewa)",
  "or": "Odia (Oriya)",
  "om": "Oromo",
  "ps": "Pashto",
  "fa": "Persian",
  "pl": "Polish",
  "pt": "Portuguese",
  "pt-br": "Brazilian Portuguese",
  "pa": "Punjabi",
  "qu": "Quechua",
  "ro": "Romanian",
  "ru": "Russian",
  "sm": "Samoan",
  "sa": "Sanskrit",
  "gd": "Scots Gaelic",
  "nso": "Sepedi",
  "sr": "Serbian",
  "st": "Sesotho",
  "sn": "Shona",
  "sd": "Sindhi",
  "si": "Sinhala (Sinhalese)",
  "sk": "Slovak",
  "sl": "Slovenian",
  "so": "Somali",
  "es": "Spanish",
  "su": "Sundanese",
  "sw": "Swahili",
  "sv": "Swedish",
  "tl": "Tagalog (Filipino)",
  "tg": "Tajik",
  "ta": "Tamil",
  "tt": "Tatar",
  "te": "Telugu",
  "th": "Thai",
  "ti": "Tigrinya",
  "ts": "Tsonga",
  "tr": "Turkish",
  "tk": "Turkmen",
  "ak": "Twi (Akan)",
  "uk": "Ukrainian",
  "ur": "Urdu",
  "ug": "Uyghur",
  "uz": "Uzbek",
  "vi": "Vietnamese",
  "cy": "Welsh",
  "xh": "Xhosa",
  "yi": "Yiddish",
  "yo": "Yoruba",
  "zu": "Zulu"
  })

module.exports.EMOJIPEDIA_PLATFORM_TYPES = [
  "apple",
  "google",
  "samsung",
  "joypixels",
  "microsoft",
  "facebook",
  "twitter",
  "whatsapp",
  "lg",
  "mozilla",
  "htc",
  "emojidex",
  "messenger",
  "softbank",
  "au-kddi",
  "docomo",
  "openmoji",
  "skype",
  "sony",
  "noto-emoji",
  "toss-face",
  "microsoft-teams",
  "animated-noto-color-emoji",
  "twitter-emoji-stickers",
  "emojipedia"
]

module.exports.EMOJIPEDIA_PLATFORM_TYPE_ALIASES = {
  "fluent": "microsoft-3D-fluent",
  "twemoji": "twitter",
  "playstation": "sony",
  "ios": "apple",
  "android": "google",
  "windows": "microsoft"
}

module.exports.GOOGLE_CLOUD_SAFETY_LABELS_NAMES = Object.freeze({
  "adult":    "Explicit Content ",
  "spoof":    "Modified Image   ",
  "medical":  "Medical Image    ",
  "violence": "Contains Violence",
  "racy":     "Lewd Content     "
})

module.exports.GOOGLE_CLOUD_SAFETY_LABELS = Object.freeze({
  "UNKNOWN": {
    icon: "question_large",
    name: "Unknown      "
  },
  "VERY_UNLIKELY": {
    icon: "exclaim_0",
    name: "Very Unlikely"
  },
  "UNLIKELY": {
    icon: "exclaim_1",
    name: "Unlikely     "
  },
  "POSSIBLE": {
    icon: "exclaim_2",
    name: "Possible     "
  },
  "LIKELY": {
    icon: "exclaim_3",
    name: "Likely       "
  },
  "VERY_LIKELY": {
    icon: "exclaim_4",
    name: "Very Likely  "
  }
})

module.exports.MAPKIT_ACTIONS = Object.freeze({
  SEARCH: "search",
  STATIC_MAP: "render"
})

module.exports.REXTESTER_LANGUAGES = Object.freeze({
  "bash": "38",
  "node": "23",
  "js": "23",
  "py2": "5",
  "py": "24",
  "java": "4",
  "lua": "14",
  "ruby": "12",
  "perl": "13",
  "go": "20",
  "kt": "43",
  "rust": "46",
  "php": "8",
  "c": "6",
  "cpp": "7",
  'cs': "1",
  "elixir": "41",
  "swift": "37",
  "bf": "44",
  "scala": "21",
  "haskell": "11"
})

module.exports.REXTESTER_COMPILER_ARGS = Object.freeze({
  "6": "-Wall -std=gnu99 -O2 -o a.out source_file.c",
  "7": "-Wall -std=c++14 -O2 -o a.out source_file.cpp",
  "11": "-o a.out source_file.hs"
})

const { Permissions } = require("detritus-client/lib/constants")

module.exports.PERMISSIONS_TEXT = Object.freeze({
  [Permissions.ADD_REACTIONS]: "Add Reactions",
  [Permissions.ADMINISTRATOR]: "Administrator",
  [Permissions.ATTACH_FILES]: "Attach Files",
  [Permissions.BAN_MEMBERS]: "Ban Members",
  [Permissions.CHANGE_NICKNAME]: "Change Nickname",
  [Permissions.CHANGE_NICKNAMES]: "Change Nicknames",
  [Permissions.CONNECT]: "Connect",
  [Permissions.CREATE_INSTANT_INVITE]: "Create Invites",
  [Permissions.DEAFEN_MEMBERS]: "Deafen Members",
  [Permissions.EMBED_LINKS]: "Embed Links",
  [Permissions.KICK_MEMBERS]: "Kick Members",
  [Permissions.MANAGE_CHANNELS]: "Manage Channels",
  [Permissions.MANAGE_EMOJIS]: "Manage Emojis",
  [Permissions.MANAGE_GUILD]: "Manage Guild",
  [Permissions.MANAGE_MESSAGES]: "Manage Messages",
  [Permissions.MANAGE_ROLES]: "Manage Roles",
  [Permissions.MANAGE_WEBHOOKS]: "Manage Webhooks",
  [Permissions.MENTION_EVERYONE]: "Mention Everyone",
  [Permissions.MOVE_MEMBERS]: "Move Members",
  [Permissions.MUTE_MEMBERS]: "Mute Members",
  [Permissions.NONE]: "None",
  [Permissions.PRIORITY_SPEAKER]: "Priority Speaker",
  [Permissions.READ_MESSAGE_HISTORY]: "Read Message History",
  [Permissions.SEND_MESSAGES]: "Send Messages",
  [Permissions.SEND_TTS_MESSAGES]: "Text-To-Speech",
  [Permissions.SPEAK]: "Speak",
  [Permissions.STREAM]: "Go Live",
  [Permissions.USE_EXTERNAL_EMOJIS]: "Use External Emojis",
  [Permissions.USE_VAD]: "Voice Auto Detect",
  [Permissions.VIEW_AUDIT_LOG]: "View Audit Logs",
  [Permissions.VIEW_CHANNEL]: "View Channel",
  [Permissions.VIEW_GUILD_ANALYTICS]: "View Server Insights"
});

module.exports.YOUTUBE_CATEGORIES = {
  "music": "10",
  "animals": "15",
  "sports": "17",
  "travel": "19",
  "gaming": "20",
  "comedy": "34",
  "news": "25",
  "howto": "26",
  "education": "27",
  "science": "28",
  "movies": "30",
  "animation": "31",
  "documentary": "35",
  "horror": "39",
  "fantasy": "40",
  "shorts": "42",
  "shows": "43"
}

// Special character that allows for fully hidden masked links on all (supported) platforms.
module.exports.HIDDEN_MASKED_LINK_CHARACTER = "󠄴";